name: DR_SSL
channels:
  - pytorch
  - conda-forge
  - defaults
  - anaconda
  - pyg
dependencies:
  - python==3.9
  - pip==21.3.1
  - pytorch==1.9.0
  - torchvision==0.10.0
  - cudatoolkit==11.1.1
  - pyg==2.0.2
  - pip:
      - -r requirements.txt