name: final_project_8735
channels:
  - pytorch
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python==3.8
  - pip==21.1.2
  - pytorch==1.8.0
  - torchvision==0.9.0
  - torchaudio==0.8.0
  - cudatoolkit=11.2
  - pip:
      - -r requirements.txt
      - torch-scatter -f https://data.pyg.org/whl/torch-1.8.0+cu111.html
      - torch-sparse -f https://data.pyg.org/whl/torch-1.8.0+cu111.html
      - torch-cluster -f https://data.pyg.org/whl/torch-1.8.0+cu111.html
      - torch-spline-conv -f https://data.pyg.org/whl/torch-1.8.0+cu111.html
      - torch-geometric -f https://data.pyg.org/whl/torch-1.8.0+cu111.html