name: DR_SSL
channels:
  - pytorch
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python==3.9
  - pip==21.3.1
  - pytorch==1.9.0
  - torchvision==0.10.0
  - cudatoolkit=11.1.1
  - pip:
      - -r requirements.txt
      - torch-scatter -f https://data.pyg.org/whl/torch-1.9.0+cu111.html
      - torch-sparse -f https://data.pyg.org/whl/torch-1.9.0+cu111.html
      - torch-cluster -f https://data.pyg.org/whl/torch-1.9.0+cu111.html
      - torch-spline-conv -f https://data.pyg.org/whl/torch-1.9.0+cu111.html
      - torch-geometric -f https://data.pyg.org/whl/torch-1.9.0+cu111.html