#+TITLE: Semi-Supervised Graph Learning Meets Dimensionality Reduction
#+SUBTITLE: Final Project for Unsupervised Learning in Fall 2021
#+AUTHOR: Alex Morehead & Watchanan Chantapakul
#+BEAMER_THEME: metropolis
#+BEAMER_HEADER: \usepackage{tikz}
#+BEAMER_HEADER: \institute{\includegraphics[width=2.8cm]{MU_Eps.png}}
#+OPTIONS: toc:nil
#+LATEX_CMD: xetex

#+BEAMER_HEADER: \addtobeamertemplate{title page}{}{%
#+BEAMER_HEADER: \begin{tikzpicture}[remember picture,overlay]
#+BEAMER_HEADER: \node[anchor=north east,yshift=2pt] at (current page.north east) {\includegraphics[height=0.9cm]{UM.png}};
#+BEAMER_HEADER: \end{tikzpicture}}

#+BEAMER_HEADER: \addtobeamertemplate{frametitle}{}{%
#+BEAMER_HEADER: \begin{tikzpicture}[remember picture,overlay]
#+BEAMER_HEADER: \node[anchor=north east,yshift=2pt] at (current page.north east) {\includegraphics[height=0.8cm]{UM.png}};
#+BEAMER_HEADER: \end{tikzpicture}}
#+OPTIONS: H:2

* Project Proposal
** Abstract
Semi-supervised learning (SSL) has recently received increased attention by
machine learning researchers cite:DBLP:journals/corr/KipfW16. By enabling
effective propagation of known labels in graph-based deep learning (GDL)
algorithms, SSL is poised to become an increasingly-used technique in GDL in the
coming years. However, there are currently few explorations in the graph-based
SSL literature on exploiting classical dimensionality reduction techniques for
improved label propagation cite:YU20121119, cite:hong2019learning. In this work,
we propose to investigate the use of dimensionality reduction techniques such as
PCA, t-SNE, and UMAP to see their effect on the performance of graph neural
networks (GNNs) designed for semi-supervised propagation of node labels. Our
study will make use of benchmark semi-supervised GDL datasets such as the Cora
and Citeseer datasets to allow meaningful comparisons of the representations
learned by each algorithm when paired with a dimensionality reduction technique.
Our node classification results will be reported in terms of cross entropy loss,
precision, recall, and F1 score.
** Responsibilities
1. Alex Morehead - Responsible for Graph Deep Learning Tasks
2. Watchanan Chantapakul - Responsible for Dimensionality Reduction Tasks
** Timeline
- 11/11/2021: Have baseline graph deep learning environment for training models completed
- 11/16/2021: Have dimensionality reduction algorithms selected
- 11/18/2021: Have rough first versions of each dimensionality reduction algorithm implemented
- 11/23/2021: Have underway integration of dimensionality reduction algorithms into our deep learning environment
- 11/25/2021: Have rough first version of deep learning models training with $a priori$ dimensionality reduction
- 11/30/2021: Have underway refinement of deep learning models and their results
- 12/02/2021: Have analysis of model results and presentation preparation underway
- 12/07/2021: Present study's results
- 12/09/2021: Have composition of final project report underway
- 12/14/2021: Have first few drafts of final project report completed
- 12/16/2021: Submit final project report

bibliographystyle:unsrt
bibliography:../../../../../../../Bibliographies/mindmeld.bib
